name: solsi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/inicio/
    - assets/images/homePage/
    - assets/images/fPhase/
    - assets/images/sPhase/
